### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by brunozrk** [fnando/burgundy#2]
I tried to use `pry` in a method of my `Presenter`, but it stopped at `method_missing` instead the method that I put `binding.pry`

Have you got this error?

**Comment by fnando** [comment]
Actually, I'm seeing this behavior a lot in pry. I think is due to some broken update or even Ruby 2.2 support. Same thing happens when I try to debug a RSpec spec; it stops on some line of RSpec and not the actual place I added the breakpoint.

Need to investigate more.
